### ISSUE TITLE
[issue register] 'RunLoop.Mode.default' has been renamed, 'RunLoop.Mode.tracking' has been renamed'

### ISSUE THREAD

**Issue by jungseungyeo** [EFPrefix/EFCountingLabel#12]
RunLoop.Mode.default has been renamed to RunLoopMode.defaultRunLoopMode,
RunLoop.Mode.tracking has been renamed to RunLoopMode.UITrackingRunLoopMode

change your grammar

**Comment by EyreFree** [comment]
Are you sure you are using Swift 4.2?

```
'RunLoopMode' has been renamed to 'RunLoop.Mode'
Replace 'RunLoopMode' with 'RunLoop.Mode'

'RunLoopMode' was obsoleted in Swift 4.2 (Foundation.RunLoopMode)
```

![](https://upload-images.jianshu.io/upload_images/1018190-457ddc2acf628954.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by jungseungyeo** [comment]
I'm sorry. It's my fault.....
