### ISSUE TITLE
Change GitHub description to be HTTPS

### ISSUE THREAD

**Issue by Coeur** [EFPrefix/EFCountingLabel#21]
A reminder from #15:

You'll need to change the GitHub description manually to make it HTTPS:
<img width="759" alt="screen shot 2019-03-07 at 15 20 28" src="https://user-images.githubusercontent.com/839992/53938953-bf73af00-40ec-11e9-888a-570a506b94a8.png">

**Comment by EyreFree** [comment]
@Coeur 

Fixed, thanks for reminding, 🙏
