### ISSUE TITLE
currentValue() get error

### ISSUE THREAD

**Issue by SpectatorNan** [EFPrefix/EFCountingLabel#25]
#### Description

[Tell us about the issue]
![image](https://user-images.githubusercontent.com/13959374/58942641-bad49a80-87b0-11e9-9c56-e8d9478cc42e.png)

当label滚动完毕之后 去通过  currentValue() 方法 获取当前值 得到的结果为 0

**Comment by SpectatorNan** [comment]
![image](https://user-images.githubusercontent.com/13959374/58943037-83b2b900-87b1-11e9-9de6-87b0421ba0cc.png)
![image](https://user-images.githubusercontent.com/13959374/58943054-8c0af400-87b1-11e9-8749-4ab577b80e24.png)
查看源码好像 动画结束之后  获取的 结果将为0

**Comment by SpectatorNan** [comment]
setTextValue() 检查为这个方法 设置初始值的时候 不能通过该方法获取当前值

**Comment by EyreFree** [comment]
@SpectatorNan

我们更新了 5.1.1 版本，你可以试一下这个问题是否已被解决？
