### ISSUE TITLE
v5.1.0 introduces some breaking changes

### ISSUE THREAD

**Issue by KyleGoslan** [EFPrefix/EFCountingLabel#27]
```swift
countFromCurrentValueTo(CGFloat(total))
```

Seems to be broken in 5.0.1

**Comment by EyreFree** [comment]
@KyleGoslan 

There is no v[5.0.1](https://github.com/EFPrefix/EFCountingLabel/releases/tag/5.0.1), did you mean [5.1.0](https://github.com/EFPrefix/EFCountingLabel/releases/tag/5.1.0)?

**Comment by KyleGoslan** [comment]
Yes, sorry. Typo.

**Comment by EyreFree** [comment]
@KyleGoslan 

We tried to fix this problem in version [5.1.1](https://github.com/EFPrefix/EFCountingLabel/releases/tag/5.1.1). Maybe you can try it out?

**Comment by KyleGoslan** [comment]
> perhaps some default values are not set.

There was definitely a default value. 

v [5.1.1](https://github.com/EFPrefix/EFCountingLabel/releases/tag/5.1.1) fixes it with no code changes my end. Good work and thanks.
