### ISSUE TITLE
README says the default duration is 2 seconds, but it's 0 seconds (no animation)

### ISSUE THREAD

**Issue by ElegyD** [EFPrefix/EFCountingLabel#28]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [README.md](https://github.com/EFPrefix/EFCountingLabel/blob/master/README.md), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/EFPrefix/EFCountingLabel/issues?utf8=%E2%9C%93&q=is%3Aissue), but did find a same one.

### Issue Description

README says the default duration is 2 seconds, but it's 0 seconds (no animation)

#### Description

README says:
> You can also specify the duration. The default is 2.0 seconds.

Code says:
https://github.com/EFPrefix/EFCountingLabel/blob/64d66c41c3f1562c3029e0aa8a2e136cdc796df4/EFCountingLabel/Classes/EFCount.swift#L46
https://github.com/EFPrefix/EFCountingLabel/blob/64d66c41c3f1562c3029e0aa8a2e136cdc796df4/EFCountingLabel/Classes/EFCount.swift#L50
https://github.com/EFPrefix/EFCountingLabel/blob/64d66c41c3f1562c3029e0aa8a2e136cdc796df4/EFCountingLabel/Classes/EFCount.swift#L54

#### Reproduce

Documentation issue

**Comment by EyreFree** [comment]
@ElegyD 

Thanks for pointing out the mistake, it has been corrected in [5.1.1](https://github.com/EFPrefix/EFCountingLabel/releases/tag/5.1.1).
