### ISSUE TITLE
Value of type 'EFCountingLabel' has no member 'format'

### ISSUE THREAD

**Issue by ciumexan** [EFPrefix/EFCountingLabel#29]
### Issue Description

Value of type 'EFCountingLabel' has no member 'format'

#### Description

upgraded to 5.1.1

#### Reproduce

![Screenshot 2019-11-17 at 15 28 08](https://user-images.githubusercontent.com/3225668/69009611-e4dcdc00-094e-11ea-8761-7c4ab4ba9714.png)

#### Other Comment

Upgraded from EFCountingLabel (5.0.0) to EFCountingLabel (5.1.1)

**Comment by EyreFree** [comment]
@ciumexan 

You need to use `setUpdateBlock` instead, for example:

```swift
myLabel.setUpdateBlock { value, label in
    label.text = String(format: "%.2f%%", value)
}
```
