### ISSUE TITLE
iOS 15 beta compatibility

### ISSUE THREAD

**Issue by skware** [EFPrefix/EFCountingLabel#33]
### Issue Description

EFCountingLabel does not compile in Xcode 13 due to an ambiguous usage of pow in update of EFTimingFunction
Changing the method signature to func update(_ time: TimeInterval) -> TimeInterval   solves the issue

**Comment by skware** [comment]
nice thanks

**Comment by EyreFree** [comment]
@skware 

Fixed in [5.1.3](https://github.com/EFPrefix/EFCountingLabel/releases/tag/5.1.3).
