### ISSUE TITLE
Compiler error "Ambiguous use of 'pow'" in xCode beta

### ISSUE THREAD

**Issue by perbrondum** [EFPrefix/EFCountingLabel#34]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [ ] I have read the [README.md](https://github.com/EFPrefix/EFCountingLabel/blob/master/README.md), but there is no information I need.
- [ ] I have searched in [existing issues](https://github.com/EFPrefix/EFCountingLabel/issues?utf8=%E2%9C%93&q=is%3Aissue), but did find a same one.

### Issue Description
Xcode 13 Beta 1 compiler error: "Ambiguous use of 'pow'" in public enum EFTimingFunction: EFTiming {
#### Description

[Tell us about the issue]

#### Reproduce
compile EFCountingLabel
[The steps to reproduce this issue. What are the parameters, where did you put your code, etc.]
compile EFCountingLabel
#### Other Comment

[Add anything else here]

**Comment by EyreFree** [comment]
@perbrondum 

Fixed in [5.1.3](https://github.com/EFPrefix/EFCountingLabel/releases/tag/5.1.3).
